# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Hockeyapp"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    	ensure_git_branch(branch: 'master')
      increment_build_number
      git_commit(path: ["./"],
        message: "Version Bump")

      gym(
      configuration: "Release",
      scheme: "NBADaily",
      silent: true,
      clean: true,
      export_method: "ad-hoc"  
      )
    hockey(
      api_token: "2bfe4ba193384e49bcc9a4215481585a",
      public_identifier: "b359a554c37c498ca460a50c836fe624",
      notes: "Changelog",
      notify: '0',
      notes:git_branch + ' (Uploaded via fastlane).'
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    reset_git_repo force: true
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
